descriptor-schema-version: "2.0"
 
info:
  name: Echo Server App
  description: "IOx Java PaaS style Application for Http Echo Server functionality"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  type: paas
          
  resources:
      profile: c1.medium
      network:
        -
          interface-name: eth0
          ports:
            tcp:
            - 8080
    
  startup: 
    runtime: java-se-embedded-cp3
    runtime-version: 1.8
    runtime-options: 
      classpath: "$CAF_APP_PATH/:$CAF_APP_PATH/lib/*:$CAF_APP_PATH/lib/classes"
      java-options: -Djava.util.logging.config.file=logging.properties -Djava.net.preferIPv4Stack=true
    target: sample.echoserver.EchoServer
